[package]
name = "DeityGB"
version = "0.1.0"
authors = ["jason"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Keeping here for future reference in case it's needed

[dependencies]
ggez = "0.5.1"
